version: '3.8'

services:
  pygeoapi:
    image: geopython/pygeoapi
    ports:
      - "5000:80"
    volumes:
      - ./pygeoapi-config.yml:/pygeoapi/local.config.yml
      - ./custom_templates/:/pygeoapi/custom_templates/
      - ./catalogue.tinydb:/pygeoapi/catalogue.tinydb
    depends_on:
      postgres:
        condition: service_healthy
      python_scripts:
        condition: service_completed_successfully
      

  postgres:
    image: postgis/postgis
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"

  python_scripts:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./pygeoapi-config.yml:/app/pygeoapi-config.yml
      - ./.env:/.env
      - ./catalogue.tinydb:/app/catalogue.tinydb