version: '3.8'

services:
  pygeoapi:
    image: geopython/pygeoapi
    ports:
      - "5001:80"
    volumes:
      - ./pygeoapi-config.yml:/pygeoapi/local.config.yml
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgis/postgis
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "my_geospatial_db"]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"